# Generated by Django 4.1.2 on 2022-11-02 04:09

import Post.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tmp_name",
                    models.CharField(
                        default=Post.models.generate_random_name, max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("post_title", models.TextField()),
                ("post_content", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                ("watches", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("tag", models.CharField(default="default", max_length=30)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draft_title", models.TextField()),
                ("draft_content", models.TextField()),
                ("tag", models.CharField(default="default", max_length=30)),
                (
                    "drafted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("likes", models.IntegerField(default=0)),
                ("return_to", models.IntegerField(default=-1)),
                (
                    "tmp_name",
                    models.CharField(
                        default=Post.models.generate_random_name, max_length=20
                    ),
                ),
                (
                    "comment_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment_under",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Post.post"
                    ),
                ),
            ],
        ),
    ]
