# Generated by Django 4.1.2 on 2022-11-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="return_to",
        ),
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_comment",
                to="Post.comment",
                verbose_name="commeng on other comment",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="browser",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_browser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="browsered by some user",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="favorite",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_favorite",
                to=settings.AUTH_USER_MODEL,
                verbose_name="collected by some user",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="comment by some user",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_under",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comment",
                to="Post.post",
                verbose_name="comment under some post",
            ),
        ),
        migrations.AlterField(
            model_name="draft",
            name="drafted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_draft",
                to=settings.AUTH_USER_MODEL,
                verbose_name="draft drafted by some user",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="posted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_post",
                to=settings.AUTH_USER_MODEL,
                verbose_name="posted by some user",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.CharField(
                choices=[
                    ("s", "life is meaningless"),
                    ("h", "I am a procrastinator"),
                    ("i", "want to die"),
                    ("t", "venomous!"),
                    ("a", "I am a piece of shit"),
                    ("b", "I am the black sheep"),
                ],
                default="s",
                max_length=30,
            ),
        ),
    ]
