# Generated by Django 4.1.2 on 2022-11-05 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Post", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="vote",
        ),
        migrations.AddField(
            model_name="post",
            name="downvote",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_downvote",
                to=settings.AUTH_USER_MODEL,
                verbose_name="downvote by some user",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="hates",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="upvote",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_upvote",
                to=settings.AUTH_USER_MODEL,
                verbose_name="upvote by some user",
            ),
        ),
        migrations.AlterField(
            model_name="draft",
            name="draft_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="draft",
            name="tag",
            field=models.CharField(
                choices=[
                    ("s", "life is meaningless"),
                    ("h", "I am a procrastinator"),
                    ("i", "want to die"),
                    ("t", "venomous!"),
                    ("a", "I am a piece of shit"),
                    ("b", "I am the black sheep"),
                ],
                default="s",
                max_length=30,
            ),
        ),
    ]
