# Generated by Django 4.1 on 2022-11-05 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Post", "0003_remove_post_vote_post_downvote_post_hates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="downvote",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvote_comment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="downvote by some user",
            ),
        ),
        migrations.AddField(
            model_name="comment", name="hates", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="upvote",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvote_comment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="upvote by some user",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="downvote",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvote_post",
                to=settings.AUTH_USER_MODEL,
                verbose_name="downvote by some user",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="upvote",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvote_post",
                to=settings.AUTH_USER_MODEL,
                verbose_name="upvote by some user",
            ),
        ),
    ]
