# Generated by Django 4.1 on 2022-11-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Post", "0004_post_stars_post_vote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="last_modified", new_name="comment_time",
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_comment",
                to="Post.comment",
                verbose_name="commeng on other comment",
            ),
        ),
    ]
