# Generated by Django 4.1 on 2022-11-06 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Post", "0004_comment_downvote_comment_hates_comment_upvote_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="favorite",),
        migrations.AddField(
            model_name="post",
            name="collection",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_collection",
                to=settings.AUTH_USER_MODEL,
                verbose_name="collected by some user",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_comment",
                to="Post.comment",
                verbose_name="commeng on other comment",
            ),
        ),
    ]
