# Generated by Django 4.1 on 2022-11-06 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("User", "0004_alter_user_aboutme"),
        ("Post", "0005_remove_post_favorite_post_collection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="browser_history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("browser_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="browser",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_browser",
                through="Post.browser_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="browsered by some user",
            ),
        ),
        migrations.AddField(
            model_name="browser_history",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Post.post"
            ),
        ),
        migrations.AddField(
            model_name="browser_history",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
