# Generated by Django 4.1 on 2022-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_content", models.TextField(default="")),
                ("comment_time", models.DateTimeField(auto_now_add=True)),
                ("likes", models.IntegerField(default=0)),
                ("hates", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draft_title", models.TextField()),
                ("draft_content", models.TextField(blank=True, null=True)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("s", "life is meaningless"),
                            ("h", "I am a procrastinator"),
                            ("i", "want to die"),
                            ("t", "venomous!"),
                            ("a", "I am a piece of shit"),
                            ("b", "I am the black sheep"),
                        ],
                        default="s",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now_add=True)),
                ("post_title", models.TextField()),
                ("post_content", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                ("hates", models.IntegerField(default=0)),
                ("watches", models.IntegerField(default=0)),
                ("stars", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("s", "life is meaningless"),
                            ("h", "I am a procrastinator"),
                            ("i", "want to die"),
                            ("t", "venomous!"),
                            ("a", "I am a piece of shit"),
                            ("b", "I am the black sheep"),
                        ],
                        default="s",
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
