# Generated by Django 4.1 on 2022-11-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Post", "0004_collection_time_browser_history"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="comments",),
    ]
