# Generated by Django 4.1.2 on 2022-11-06 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Post", "0005_remove_post_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="browser_history",
            name="browser_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="collection_time",
            name="star_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="post",
            name="browser",
        ),
        migrations.AddField(
            model_name="post",
            name="browser",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_browser",
                through="Post.browser_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="browsered by some user",
            ),
        ),
        migrations.RemoveField(
            model_name="post",
            name="collection",
        ),
        migrations.AddField(
            model_name="post",
            name="collection",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_collection",
                through="Post.collection_time",
                to=settings.AUTH_USER_MODEL,
                verbose_name="collected by some user",
            ),
        ),
    ]
