# Generated by Django 4.1.2 on 2022-11-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="reg_date",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
        ),
    ]
