# Generated by Django 4.1.2 on 2022-11-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_remove_user_admin_remove_user_reg_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
    ]
