# Generated by Django 4.1.2 on 2022-11-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Post", "__first__"),
        ("User", "0003_remove_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="browse_history",
            field=models.ManyToManyField(related_name="his", to="Post.post"),
        ),
        migrations.AddField(
            model_name="user",
            name="collections",
            field=models.ManyToManyField(related_name="fav", to="Post.post"),
        ),
    ]
