# Generated by Django 4.1.2 on 2022-11-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_user_aboutme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="aboutme",
            field=models.CharField(
                default="This twat nigga decides to say nothing about himself, a fat ass made goofy son of a bitch.",
                max_length=150,
            ),
        ),
    ]
