# Generated by Django 4.1.2 on 2022-11-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_user_browse_history_user_collections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="browse_history",
        ),
        migrations.RemoveField(
            model_name="user",
            name="collections",
        ),
    ]
