# Generated by Django 4.1.2 on 2022-11-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_user_date_joined_user_is_active_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email"),
        ),
    ]
