# Generated by Django 4.1.2 on 2022-11-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0009_user_groups_user_is_verified_user_user_permissions"),
        ("User", "0009_user_groups_user_user_permissions"),
    ]

    operations = []
